=== jensaug/java-poi-utility/target/classes/schema/questionnaire.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "_id": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "group": {
            "type": "string"
        },
        "customCodes": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "code": {
                        "type": "string"
                    },
                    "vendor": {
                        "type": "string"
                    }
                },
                "additionalProperties": false,
                "required": [
                    "code",
                    "vendor"
                ]
            }
        },
        "comments": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "tags": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "language": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                }
            },
            "additionalProperties": false,
            "required": [
                "name",
                "code"
            ]
        },
        "questions": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "text": {
                        "type": "string"
                    },
                    "explanation": {
                        "type": "string"
                    },
                    "group": {
                        "type": "string"
                    },
                    "part": {
                        "type": "string"
                    },
                    "elaboration": {
                        "type": "object",
                        "properties": {
                            "text": {
                                "type": "string"
                            },
                            "reference": {
                                "type": "string"
                            }
                        },
                        "additionalProperties": false,
                        "required": [
                            "text"
                        ]
                    },
                    "choices": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "value": {
                                    "type": "string"
                                },
                                "text": {
                                    "type": "string"
                                }
                            },
                            "additionalProperties": false,
                            "required": [
                                "value"
                            ]
                        }
                    },
                    "module": {
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "shortName": {
                                "type": "string"
                            },
                            "question": {
                                "type": "object",
                                "properties": {
                                    "comparableText": {
                                        "type": "string"
                                    },
                                    "dimension": {
                                        "type": "string"
                                    },
                                    "choiceFreeText": {
                                        "type": "boolean"
                                    },
                                    "choices": {
                                        "type": "array",
                                        "items": {
                                            "type": "object",
                                            "properties": {
                                                "value": {
                                                    "type": "string"
                                                },
                                                "weight": {
                                                    "type": ["number", "null"]
                                                }
                                            },
                                            "additionalProperties": false,
                                            "required": [
                                                "value"
                                            ]
                                        }
                                    },
                                    "customCodes": {
                                        "type": "array",
                                        "items": {
                                            "type": "object",
                                            "properties": {
                                                "code": {
                                                    "type": "string"
                                                },
                                                "vendor": {
                                                    "type": "string"
                                                }
                                            },
                                            "additionalProperties": false,
                                            "required": [
                                                "code",
                                                "vendor"
                                            ]
                                        }
                                    },
                                    "comments": {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        }
                                    },
                                    "tags": {
                                        "type": "array",
                                        "items": {
                                            "type": "string"
                                        }
                                    }
                                },
                                "additionalProperties": false,
                                "required": [
                                    "comparableText"
                                ],
                                "anyOf": [
                                    {
                                        "required": ["choices"]
                                    },
                                    {
                                        "required": ["choiceFreeText"]
                                    }
                                ]
                            }
                        },
                        "additionalProperties": false,
                        "required": [
                            "name",
                            "shortName",
                            "question"
                        ]
                    }
                },
                "additionalProperties": false,
                "required": [
                    "text",
                    "module"
                ]
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "name",
        "language",
        "questions"
    ]
}

=== jensaug/java-poi-utility/src/main/resources/json-samples/questionnaire.json
{
    "name": "questionnaire-sample",
    "group": "Primärvård",
    "language": {
        "name": "Svenska",
        "code": "sv_SE"
    },
    "customCodes": [
        {
            "code": "DBNVNA05YNNNA1N000054",
            "vendor": "icquality"
        }
    ],
    "comments": [
        "Detta frågeformulär är ett exempel"
    ],
    "tags": [
        "ex"
    ],
    "questions": [
        {
            "text": "Skulle du: rekommendera hälso-/vårdcentralen till vänner och bekanta?",
            "explanation": "Var god skriv inom rutans ramar, texta tydligt.",
            "group": "Skulle du:",
            "part": "rekommendera hälso-/vårdcentralen till vänner och bekanta?",
            "elaboration": {
                "text": "Utveckla gärna ditt svar på sista sidan",
                "reference": "Har du andra synpunkter eller vill utveckla dina svar?"
            },
            "choices": [
                {
                    "value": "1",
                    "text": "Nej, inte alls"
                },
                {
                    "value": "2"
                },
                {
                    "value": "3"
                },
                {
                    "value": "4"
                },
                {
                    "value": "5",
                    "text": "Ja, helt och hållet"
                },
                {
                    "value": "6",
                    "text": "Ej aktuellt"
                }
            ],
            "module": {
                "name": "questionmodule-sample",
                "shortName": "qms",
                "question": {
                    "comparableText": "Skulle du rekommendera ${verksamheten} till vänner och bekanta?",
                    "dimension": "Delaktighet och involvering",
                    "choiceFreeText": false,
                    "choices": [
                        {
                            "value": "1",
                            "weight": -1
                        },
                        {
                            "value": "2",
                            "weight": -1
                        },
                        {
                            "value": "3",
                            "weight": 0
                        },
                        {
                            "value": "4",
                            "weight": 1
                        },
                        {
                            "value": "5",
                            "weight": 1
                        },
                        {
                            "value": "6"
                        }
                    ],
                    "customCodes": [
                        {
                            "code": "DBNVNA05YNNNA1N000054",
                            "vendor": "icquality"
                        }
                    ],
                    "comments": [
                        "Denna fråga är väldigt fin",
                        "Jag tycker om denna fråga"
                    ],
                    "tags": [
                        "ex"
                    ]
                }
            }
        },
        {
            "text": "Har du andra synpunkter eller vill utveckla dina svar?",
            "module": {
                "name": "questionmodule-sample",
                "shortName": "qms",
                "question": {
                    "comparableText": "Har du andra synpunkter eller vill utveckla dina svar?",
                    "choiceFreeText": true
                }
            }
        }
    ]
}
