=== jensaug/java-poi-utility/target/classes/schema/statisticOption.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "name": {
            "type": "string"
        },
        "views": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "value": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "published": {
                        "type": "object",
                        "properties": {
                            "public": {
                                "type": "string",
                                "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}$"
                            },
                            "internal": {
                                "type": "string",
                                "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}$"
                            }
                        },
                        "anyOf": [
                            {
                                "required": ["public"]
                            },
                            {
                                "required": ["internal"]
                            }
                        ],
                        "additionalProperties": false
                    },
                    "manualGet": {
                        "type": "boolean"
                    },
                    "aspects": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "value": {
                                    "type": "string"
                                },
                                "name": {
                                    "type": "string"
                                }
                            },
                            "required": [
                                "value"
                            ],
                            "additionalProperties": false
                        }
                    },
                    "filters": {
                        "type": "object"
                    },
                    "dimensions": {
                        "type": "object"
                    },
                    "filterGroups": {
                        "type": "object"
                    },
                    "visibleModules": {
                        "type": "object"
                    },
                    "questionGroups": {
                        "type": "object"
                    }
                },
                "required": [
                    "value",
                    "published",
                    "aspects"
                ],
                "additionalProperties": false
            }
        },
        "dimensions": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "value": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "extra": {
                        "type": "boolean"
                    }
                },
                "required": [
                    "value"
                ],
                "additionalProperties": false
            }
        },
        "filterGroups": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "value": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "tab": {
                        "type": "string"
                    },
                    "required": {
                        "type": "boolean"
                    },
                    "autoSet": {
                        "type": "boolean"
                    }
                },
                "required": [
                    "value",
                    "tab"
                ],
                "additionalProperties": false
            }
        },
        "filters": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "value": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "filterGroup": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "required": {
                        "type": "boolean"
                    },
                    "multiSelect": {
                        "type": "boolean"
                    },
                    "locked": {
                        "type": "boolean"
                    },
                    "enrichOptions": {
                        "type": "boolean"
                    },
                    "locked": {
                        "type": "object",
                        "properties": {
                            "value": {
                                "type": "string"
                            },
                            "name": {
                                "type": "string"
                            }
                        },
                        "required": ["value"],
                        "additionalProperties": false
                    },
                    "options": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "value": {
                                    "type": "string"
                                },
                                "name": {
                                    "type": "string"
                                },
                                "match": {
                                    "type": "string"
                                },
                                "selected": {
                                    "type": "boolean"
                                }
                            },
                            "anyOf": [
                                {
                                    "required": ["value", "match"]
                                },
                                {
                                    "required": ["name"]
                                }
                            ],
                            "additionalProperties": false
                        }
                    },
                    "parameter": {
                        "type": "object",
                        "properties": {
                            "field": {
                                "type": "string"
                            },
                            "type": {
                                "type": "string"
                            },
                            "eq": {
                                "type": "boolean"
                            },
                            "gte": {
                                "type": "boolean"
                            },
                            "lte": {
                                "type": "boolean"
                            }
                        },
                        "required": [
                            "field",
                            "type",
                            "eq",
                            "gte",
                            "lte"
                        ],
                        "additionalProperties": false
                    }
                },
                "required": [
                    "value"
                ],
                "oneOf": [
                    {
                        "required": ["options"]
                    },
                    {
                        "required": ["enrichOptions"]
                    },
                    {
                        "required": ["parameter"]
                    }
                ],
                "additionalProperties": false
            }
        },
        "visibleModules": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "value": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    }
                },
                "required": [
                    "value"
                ],
                "additionalProperties": false
            }
        },
        "questionGroups": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "value": {
                        "type": "string"
                    },
                    "name": {
                        "type": "string"
                    },
                    "members": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "required": [
                    "value",
                    "members"
                ],
                "additionalProperties": false
            }
        }
    },
    "required": [
        "name",
        "views",
        "dimensions",
        "filterGroups",
        "filters",
        "visibleModules",
        "questionGroups"
    ],
    "additionalProperties": false
}

=== jensaug/java-poi-utility/src/main/resources/json-samples/statisticOption.json
{
    "name": "Primärvård 2015",
    "views": [ 
        {
            "value": "public",
            "name": "Publik återföring",
            "manualGet": true,
            "published": {
                "public": "1970-01-01T00:00",
                "internal": "1970-01-01T00:00"
            },
            "aspects": [ 
                {
                    "value": "public",
                    "name": "Publik"
                }
            ],
            "filterGroups": {
                "advanced": null,
                "base": {
                    "autoSet": true
                },
                "organisations": {
                    "tab": "Basfilter"
                }
            },
            "filters": {
                "age": null,
                "ageGroup": null,
                "sex": {
                    "multiSelect": true
                },
                "selectionCriteria": {
                    "locked": {
                        "value": "Läkarbesök"
                    }
                },
                "version": {
                    "locked": {
                        "value": "vuxen",
                        "name": "Vuxen"
                    }
                }
            },
            "dimensions": {
                "Övrigt": null
            }
        }, 
        {
            "value": "internal",
            "name": "Intern återföring",
            "published": {
                "internal": "1970-01-01T00:00"
            },
            "aspects": [ 
                {
                    "value": "public",
                    "name": "Publik"
                }, 
                {
                    "value": "internal",
                    "name": "Intern"
                }, 
                {
                    "value": "hsa",
                    "name": "HSA"
                }, 
                {
                    "value": "sr_counties",
                    "name": "Län"
                }
            ]
        }
    ],
    "dimensions": [ 
        {
            "value": "Helhetsintryck"
        }, 
        {
            "value": "Emotionellt stöd"
        }, 
        {
            "value": "Delaktighet och involvering"
        }, 
        {
            "value": "Respekt och bemötande"
        }, 
        {
            "value": "Kontinuitet och koordinering"
        }, 
        {
            "value": "Information och kunskap"
        }, 
        {
            "value": "Tillgänglighet"
        }, 
        {
            "value": "Övrigt",
            "extra": true
        }
    ],
    "filterGroups": [ 
        {
            "name": "Organisationer",
            "value": "organisations",
            "tab": "Organisationer",
            "required": true,
            "autoSet": true
        }, 
        {
            "name": "Filter",
            "value": "base",
            "required": true,
            "tab": "Basfilter"
        }, 
        {
            "name": "Avancerade filter",
            "value": "advanced",
            "required": true,
            "tab": "Avancerade filter"
        }
    ],
    "visibleModules": [ 
        {
            "value": "Dimensioner - spindelgraf"
        }, 
        {
            "value": "Dimensioner - stapeldiagram"
        }, 
        {
            "value": "Dimensioner - tabell"
        }, 
        {
            "value": "Svarsfrekvens - stapeldiagram"
        }, 
        {
            "value": "Utskick - stapeldiagram"
        }, 
        {
            "value": "Supergraf"
        }
    ],
    "filters": [ 
        {
            "value": "organisations",
            "name": "Organisation",
            "filterGroup": "organisations",
            "required": true,
            "multiSelect": true,
            "enrichOptions": true
        }, 
        {
            "value": "selectionCriteria",
            "name": "Urvalskriterier",
            "filterGroup": "advanced",
            "required": true,
            "locked": {
                "value": "Läkarbesök",
                "name": "Läkarbesök"
            },
            "options": [ 
                {
                    "name": "Alla",
                    "selected": true
                }, 
                {
                    "value": "Läkarbesök",
                    "name": "Läkarbesök"
                }, 
                {
                    "value": "Sjuksköterskebesök",
                    "name": "Sjuksköterskebesök"
                }
            ]
        }, 
        {
            "value": "version",
            "name": "Enkätversion",
            "filterGroup": "advanced",
            "required": true,
            "options": [ 
                {
                    "name": "Alla",
                    "selected": true
                }, 
                {
                    "value": "vuxen",
                    "name": "Vuxen"
                }, 
                {
                    "value": "vårdnadshavare",
                    "name": "Vårdnadshavare"
                }
            ]
        }, 
        {
            "value": "sex",
            "name": "Kön",
            "filterGroup": "base",
            "required": true,
            "multiSelect": false,
            "description": "Välj kön på respondenterna",
            "options": [ 
                {
                    "name": "Alla",
                    "selected": true
                }, 
                {
                    "value": "female",
                    "name": "Kvinnor",
                    "match": "'respondent.metadata.gender':'female'"
                }, 
                {
                    "value": "male",
                    "name": "Män",
                    "match": "'respondent.metadata.gender':'male'"
                }
            ]
        }, 
        {
            "value": "age",
            "name": "Ålder",
            "filterGroup": "advanced",
            "parameter": {
                "field": "'respondent.metadata.ageAtVisit'",
                "type": "number",
                "eq": true,
                "lte": true,
                "gte": true
            }
        }, 
        {
            "value": "ageGroup",
            "name": "Åldersgrupp",
            "filterGroup": "base",
            "required": true,
            "options": [ 
                {
                    "name": "Alla",
                    "selected": true
                }, 
                {
                    "value": "0-4",
                    "name": "0-4",
                    "match": "'respondent.metadata.ageAtVisit':{$gte:0}, 'respondent.metadata.ageAtVisit':{$lte:4}"
                }, 
                {
                    "value": "5-9",
                    "name": "5-9",
                    "match": "'respondent.metadata.ageAtVisit':{$gte:5}, 'respondent.metadata.ageAtVisit':{$lte:9}"
                }, 
                {
                    "value": "10-14",
                    "name": "10-14",
                    "match": "'respondent.metadata.ageAtVisit':{$gte:10}, 'respondent.metadata.ageAtVisit':{$lte:14}"
                }, 
                {
                    "value": "15-19",
                    "name": "15-19",
                    "match": "'respondent.metadata.ageAtVisit':{$gte:15}, 'respondent.metadata.ageAtVisit':{$lte:19}"
                }, 
                {
                    "value": "20-24",
                    "name": "20-24",
                    "match": "'respondent.metadata.ageAtVisit':{$gte:20}, 'respondent.metadata.ageAtVisit':{$lte:24}"
                }, 
                {
                    "value": "25-29",
                    "name": "25-29",
                    "match": "'respondent.metadata.ageAtVisit':{$gte:25}, 'respondent.metadata.ageAtVisit':{$lte:29}"
                }, 
                {
                    "value": "30-34",
                    "name": "30-34",
                    "match": "'respondent.metadata.ageAtVisit':{$gte:30}, 'respondent.metadata.ageAtVisit':{$lte:34}"
                }, 
                {
                    "value": "35-39",
                    "name": "35-39",
                    "match": "'respondent.metadata.ageAtVisit':{$gte:35}, 'respondent.metadata.ageAtVisit':{$lte:39}"
                }, 
                {
                    "value": "40-44",
                    "name": "40-44",
                    "match": "'respondent.metadata.ageAtVisit':{$gte:40}, 'respondent.metadata.ageAtVisit':{$lte:44}"
                }, 
                {
                    "value": "45-49",
                    "name": "45-49",
                    "match": "'respondent.metadata.ageAtVisit':{$gte:45}, 'respondent.metadata.ageAtVisit':{$lte:49}"
                }, 
                {
                    "value": "50-54",
                    "name": "50-54",
                    "match": "'respondent.metadata.ageAtVisit':{$gte:50}, 'respondent.metadata.ageAtVisit':{$lte:54}"
                }, 
                {
                    "value": "55-59",
                    "name": "55-59",
                    "match": "'respondent.metadata.ageAtVisit':{$gte:55}, 'respondent.metadata.ageAtVisit':{$lte:59}"
                }, 
                {
                    "value": "60-64",
                    "name": "60-64",
                    "match": "'respondent.metadata.ageAtVisit':{$gte:60}, 'respondent.metadata.ageAtVisit':{$lte:64}"
                }, 
                {
                    "value": "65-69",
                    "name": "65-69",
                    "match": "'respondent.metadata.ageAtVisit':{$gte:65}, 'respondent.metadata.ageAtVisit':{$lte:69}"
                }, 
                {
                    "value": "70-74",
                    "name": "70-74",
                    "match": "'respondent.metadata.ageAtVisit':{$gte:70}, 'respondent.metadata.ageAtVisit':{$lte:74}"
                }, 
                {
                    "value": "75-79",
                    "name": "75-79",
