=== jensaug/java-poi-utility/target/classes/schema/suborder.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {
        "measurementRef": {
            "type": "object",
            "properties": {
                "name": {
                    "title": "Mätningsnamn",
                    "description": "Namnet på mätningen",
                    "type": "string"
                },
                "grouping": {
                    "title": "Mätningsgrupp",
                    "description": "Namn på grupp av mätningar som denna mätningen tillhör, kan vara tex Primärvård",
                    "type": "string"
                },
                "period": {
                    "title": "Mätningsperiod",
                    "description": "Den tidsperiod mätningen utförs",
                    "type": "string"
                }
            },
            "additionalProperties": false,
            "required": [
                "name",
                "grouping",
                "period"
            ]
        }
    },
    "properties": {
        "_id": {
            "type": "string"
        },
        "measurement": {
            "type": "object",
            "properties": {
                "/": {
                    "$ref": "#/definitions/measurementRef"
                }
            }
        },
        "previousMeasurement": {
            "type": "object",
            "properties": {
                "/": {
                    "$ref": "#/definitions/measurementRef"
                }
            }
        },
        "diarie": {
            "type": "object",
            "properties": {
                "number": {
                    "title": "Nummer",
                    "description": "Diarienummer",
                    "type": "string"
                },
                "link": {
                    "title": "Länk",
                    "description": "Länk till diarium",
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "hsaId": {
            "type": "string"
        },
        "hassan": {
            "type": "object"
        },
        "dn": {
            "title": "Organisationsbeskrivning",
            "description": "Organisationsbeskrivning för detta mätningsunderlag",
            "type": "string"
        },
        "previousDn": {
            "title": "Tidigare organisationsbeskrivning",
            "description": "Tidigare organisationsbeskrivning för detta mätningsunderlag",
            "type": "string"
        },
        "historicDn": {
            "title": "Historisk organisationsbeskrivning",
            "description": "Historisk organisationsbeskrivning för detta mätningsunderlag",
            "type": "string"
        },
        "status": {
            "title": "Status",
            "enum": [
                "generated",
                "invited",
                "accepted",
                "done"
            ]
        },
        "created": {
            "title": "Skapad",
            "description": "När mätningsunderlaget skapades",
            "type": "string"
        },
        "alternativeIdSystem": {
            "title": "Alternativt registersystem",
            "description": "Om ett alternativt registerstytem används anges det här",
            "type": "string"
        },
        "selectionCriterias": {
            "title": "Urvalskriterier",
            "description": "De urvalskriterier som är aktuella för mätningsunderlaget",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "title": "Namn",
                        "description": "Namn på urvalskriterie",
                        "type": "string"
                    },
                    "optOut": {
                        "title": "Avstå urvalskriterie",
                        "description": "Om mätningsunderlaget ska avstå detta urvalskriterie",
                        "type": "boolean"
                    },
                    "versions": {
                        "title": "Versioner",
                        "description": "Versioner av urvalskriterie",
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "name": {
                                    "title": "Namn",
                                    "type": "string"
                                },
                                "questionnaire": {
                                    "type": "object",
                                    "properties": {
                                        "name": {
                                            "anyOf": [{
                                                    "type": "string"
                                                }, {
                                                    "type": "null"
                                                }]
                                        }
                                    },
                                    "additionalProperties": false
                                }
                            },
                            "additionalProperties": false
                        }
                    }
                },
                "additionalProperties": false
            }
        },
        "specific": {
            "title": "Mätningsunderlagsspecifik information",
            "type": "object",
            "properties": {}
        },
        "organisations": {
            "title": "Ingående enheter",
            "description": "Ingående enheter i mätningsunderlaget",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "dn": {
                        "title": "Organisationsbeskrivning",
                        "description": "Organisationsbeskrivning för enheten",
                        "type": "string"
                    },
                    "previousDn": {
                        "title": "Tidigare organisationsbeskrivning",
                        "description": "Organisationsbeskrivning för enheten när den förra mätnignen gjordes",
                        "type": "string"
                    },
                    "historicDn": {
                        "title": "Historisk organisationsbeskrivning",
                        "description": "Organisationsbeskrivning som beskriver den historiska kopplingen för enhten",
                        "type": "string"
                    },
                    "hsaId": {
                        "title": "HSA Id",
                        "description": "HSA Id för enheten",
                        "type": "string"
                    },
                    "hassan": {
                        "title": "HSA information",
                        "description": "HSA information genom integration till HSA registret via Hassan",
                        "type": "object",
                        "properties": {}
                    },
                    "alternativeId": {
                        "title": "Alternativt id",
                        "description": "Id för enheten i det alternativa id systemet om sådant används",
                        "type": "string"
                    },
                    "publicDn": {
                        "title": "Publik organisationsbeskrivning",
                        "description": "Organisationsbeskrivnign som ska användas när resultaten ska återföras publikt",
                        "type": "string"
                    },
                    "specific": {
                        "title": "Enhetsspecifik information",
                        "description": "Enhetsspecifik information konfigurerad i mätningen",
                        "type": "object",
                        "properties": {}
                    },
                    "invitation": {
                        "title": "Inforamtion kring inbjudan",
                        "description": "Information som är kring inbjudan så som namn",
                        "type": "object",
                        "properties": {}
                    },
                    "selections": {
                        "title": "Inbjudan",
                        "description": "Hur många enkäter som ska skickas i vilka urvalskriterier",
                        "type": "object",
                        "properties": {}
                    },
                    "metadata": {
                        "title": "Metadata",
                        "description": "Metadata kring enheten",
                        "type": "object",
                        "properties": {}
                    },
                    "generatedForMovedPatient": {
                        "title": "GeneratedForMovedPatient",
                        "description": "Om sann så är denna enhet endast här pga genererade överflyttade patienter",
                        "type": "boolean"
                    }
                },
                "additionalProperties": false,
                "required": [
                    "dn"
                ]
            }
        },
        "questions": {
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "measurement",
        "dn",
        "selectionCriterias",
        "organisations"
    ]
}

=== jensaug/java-poi-utility/src/main/resources/json-samples/Extra/measurements/patientnamnden/suborders/2016-varmland.json
{
  "dn": "o=Landstinget i Värmland,st=Uppsala-Örebro regionen,c=Sverige",
  "measurement": {
    "name": "Patientnämnden 2016",
    "grouping": "Patientnämnden",
    "period": "2016"
  },
  "selectionCriterias": [
    {
      "name": "Alla",
      "versions": [
        {
          "name": "Alla",
          "questionnaire": {
            "name": "Patientnämnden 2.0"
          }
        }
      ]
    }
  ],
  "organisations": [
    {
      "dn": "o=Landstinget i Värmland,st=Uppsala-Örebro regionen,c=Sverige"
    }
  ]
}

=== jensaug/java-poi-utility/target/classes/json-samples/suborder.json
{
    "_id": "348762348263482763",
    "measurement": {
        "name": "Primärvård 2015",
        "grouping": "Primärvård",
        "period": "2015"
    },
    "previousMeasurement": {
        "name": "Primärvård 2014",
        "grouping": "Primärvård",
        "period": "2014"
    },
    "hsaId": "SE2321000131-E000000000001",
    "dn": "ou=Primärvård,o=Västra Götalandsregionen,st=Västra regionen,c=Sverige",
    "status": "generated",
    "created": "2015-01-01",
    "alternativeIdSystem": "PASIS",
    "diarie": {
        "number": "123123123",
        "link": "http://www.somesystemthathandlesthis.com"
    },
    "selectionCriterias": [
        {
            "name": "Läkarbesök",
            "versions": [
                {
                    "name": "Alla",
                    "questionnaire": {
                        "name": "Primärvård Läkarbesök Utökad v2.0"
                    }
                }
            ]
        },
        {
            "name": "Sjuksköterskebesök",
            "optOut": true,
            "versions": []
        }
    ],
    "specific": {},
    "organisations": [
        {
            "dn": "ou=Primärvård,o=Västra Götalandsregionen,st=Västra regionen,c=Sverige",
            "specific": {
                "managerEmails": [
                    "chefNarhalsan@vgr.se"
                ]
            }
        },
        {
            "dn": "ou=Område 06,ou=Primärvård Offentlig,ou=Primärvård,o=Västra Götalandsregionen,st=Västra regionen,c=Sverige",
            "specific": {
                "managerEmails": [
                    "chefOmråde6@vgr.se"
                ]
            }
        },
        {
            "dn": "ou=Närhälsan Gråbo vårdcentral,ou=Område 06,ou=Primärvård Offentlig,ou=Primärvård,o=Västra Götalandsregionen,st=Västra regionen,c=Sverige",
            "hsaId": "SE2321000131-E000000000430",
            "alternativeId": "12346",
            "previousDn": "ou=Närhälsan Gråbo vårdcentral,ou=Område 06,ou=Primärvård Offentlig,ou=Primärvård,o=Västra Götalandsregionen,st=Västra regionen,c=Sverige",
            "publicDn": "ou=Vårdcentralen Gråbo,ou=Lerum,o=Västra Götaland,c=Sverige",
            "specific": {
                "managerEmails": [
                    "chefGrabo@vgr.se"
                ]
            },
            "invitation": {
                "softName": "Gråbo Närhälsa",
                "change": "Närhälsan Gråbo vårdcentral hette tidigare Vårdcentralen Gråbo",
                "signedBy": "John Doe, överläkare"
            },
            "selections": {
                "maxAmountDoctor": 200,
                "maxAmountNurse": 100
            },
            "metadata": {
                "producer": "landstingsdriven",
                "throughput": {
                    "maxAmountDoctor": 1700,
                    "maxAmountNurse": 2900
                },
                "doneEdit": "true"
            }
        }
    ],
    "questions": [
        "Hur upplever du ${verksamheten} tillgänglighet per telefon?",
        "Kände du förtroende för den läkare som du träffade?",
        "Hur värderar du som helhet den vård/behandling du fick?"
    ]
}

=== jensaug/java-poi-utility/src/main/resources/json-samples/Extra/measurements/preem/suborders/jämtlandslanslandsting.json
{"dn":"o=Jämtlands läns landsting,st=Norra regionen,c=Sverige","measurement":{"name":"Standardiserade vårdförlopp inom cancervård 2016","grouping":"Standardiserade vårdförlopp inom cancervård","period":"2016"},"selectionCriterias":[{"name":"Alla","versions":[{"name":"vuxen","questionnaire":{"name":"Specialiserad sjukhusvård öppen vuxen 2.0"}}]}],"organisations":[{"dn":"o=Jämtlands läns landsting,st=Norra regionen,c=Sverige"},{"dn":"ou=SVF Akut myeloisk leukemi,o=Jämtlands läns landsting,st=Norra regionen,c=Sverige","previousDn":"","publicDn":"ou=Akut myeloisk leukemi (AML),ou=Region Jämtland Härjedalen,o=RCC Norr,ou=Sverige","alternativeId":"VN6","specific":{}},{"dn":"ou=SVF Cancer i urinblåsan och övre urinvägarna,o=Jämtlands läns landsting,st=Norra regionen,c=Sverige","previousDn":"","publicDn":"ou=Cancer i urinblåsan och övre urinvägarna,ou=Region Jämtland Härjedalen,o=RCC Norr,ou=Sverige","alternativeId":"VK1","specific":{}},{"dn":"ou=SVF Huvud-och halscancer,o=Jämtlands läns landsting,st=Norra regionen,c=Sverige","previousDn":"","publicDn":"ou=Huvud- och halscancer,ou=Region Jämtland Härjedalen,o=RCC Norr,ou=Sverige","alternativeId":"VA9","specific":{}},{"dn":"ou=SVF Matstrupe-och magsäckscancer,o=Jämtlands läns landsting,st=Norra regionen,c=Sverige","previousDn":"","publicDn":"ou=Matstrups- och magsäckscancer,ou=Region Jämtland Härjedalen,o=RCC Norr,ou=Sverige","alternativeId":"VB0","specific":{}},{"dn":"ou=SVF Prostatacancer,o=Jämtlands läns landsting,st=Norra regionen,c=Sverige","previousDn":"","publicDn":"ou=Prostatacancer,ou=Region Jämtland Härjedalen,o=RCC Norr,ou=Sverige","alternativeId":"VJ1","specific":{}}],"alternativeIdSystem":"KVÅ kod","specific":{"signedBy":"Björn Eriksson Regiondirektör","invitations":600}}

=== jensaug/java-poi-utility/target/classes/json-samples/Extra/sov2015-gavleborg-suborder.json
{
    "measurement": {
        "name": "Somatik öppenvård 2015 Region Gävleborg",
        "grouping": "Somatik öppenvård",
        "period": "2015"
    },
    "dn": "o=Landstinget Gävleborg,st=Uppsala-Örebro regionen,c=Sverige",
    "selectionCriterias": [
        {
            "name": "Somatik öppenvård",
            "versions": [
                {
                  "name": "Alla",
                  "questionnaire": {
                    "name": "Specialiserad sjukhusvård öppen v2.0"
                  }
                }
            ]
        }
    ],
    "organisations": [
        {
          "dn": "o=Landstinget Gävleborg,st=Uppsala-Örebro regionen,c=Sverige"
        }    
    ]
}

=== jensaug/java-poi-utility/src/main/resources/json-samples/suborder-svf.json
{
    "_id" : "58a5a64aa57b4b9473ac27e6",
    "hsaId" : "SE2321000131-E000000000001",
    "hassan" : {
        "dn" : "o=Västra Götalandsregionen,l=Västra Götalands län,c=SE",
        "postalAddress" : [ 
            "Västra Götalandsregionen", 
            "Regionens Hus", 
            "462 80", 
            "Vänersborg"
        ],
        "telephoneNumber" : "+46 501 62000",
        "mail" : "info@vgregion.se",
        "orgNo" : "232100-0131",
        "hsaIdentity" : "SE2321000131-E000000000001",
        "publicName" : "Västra Götalandsregionen",
        "name" : "Västra Götalandsregionen",
        "countyCode" : "14",
        "countyName" : "Västra Götalands Län",
        "businessClassificationCode" : [],
        "businessClassificationName" : [],
        "careType" : [],
        "hsaHealthCareUnitMember" : [],
        "nonPublicTelephoneNumber" : "+46 501 62000",
        "directoryContact" : "anne-berit.fredriksson@vgregion.se",
        "management" : "Landsting/Region",
        "isHsaHealthCareProvider" : "true",
        "hassan" : {
            "batchId" : "7a892c04-f259-11e6-8a7a-a95d56b24893"
        }
    },
    "dn" : "o=Västra Götalandsregionen,l=Västra Götalands län,c=SE",
    "measurement" : {
        "name" : "Standardiserade vårdförlopp inom cancervård 2016",
        "grouping" : "Standardiserade vårdförlopp inom cancervård",
        "period" : "2016"
    },
    "selectionCriterias" : [ 
        {
            "name" : "Alla",
            "versions" : []
        }
    ],
    "organisations" : [ 
        {
            "hsaId" : "SE2321000131-E000000000001",
            "hassan" : {
                "dn" : "o=Västra Götalandsregionen,l=Västra Götalands län,c=SE",
                "postalAddress" : [ 
                    "Västra Götalandsregionen", 
                    "Regionens Hus", 
                    "462 80", 
                    "Vänersborg"
                ],
                "telephoneNumber" : "+46 501 62000",
                "mail" : "info@vgregion.se",
                "orgNo" : "232100-0131",
                "hsaIdentity" : "SE2321000131-E000000000001",
                "publicName" : "Västra Götalandsregionen",
                "name" : "Västra Götalandsregionen",
                "countyCode" : "14",
                "countyName" : "Västra Götalands Län",
                "businessClassificationCode" : [],
                "businessClassificationName" : [],
                "careType" : [],
                "hsaHealthCareUnitMember" : [],
                "nonPublicTelephoneNumber" : "+46 501 62000",
                "directoryContact" : "anne-berit.fredriksson@vgregion.se",
                "management" : "Landsting/Region",
                "isHsaHealthCareProvider" : "true",
                "hassan" : {
                    "batchId" : "7a892c04-f259-11e6-8a7a-a95d56b24893"
                }
            },
            "dn" : "o=Västra Götalandsregionen,l=Västra Götalands län,c=SE"
        }, 
        {
            "hsaId" : "SE2321000198-031623",
            "dn" : "ou=ABC Doctor AB,ou=Bemanningsföretag,ou=Externa,o=Region Gävleborg,l=Gävleborgs län,c=SE",
            "publicDn" : "ou=ABC Doctor AB,ou=Uddevalla,o=Västra Götalands län,c=Sverige",
            "specific" : {}
        }
    ],
    "specific" : {
        "rccs" : "RCC Uppsala Örebro",
        "kvaCodes" : [ 
            "VG9", 
            "VN0", 
            "VB4", 
            "VP9", 
            "VP8", 
            "VN6", 
            "VN2"
        ],
        "signedBy" : "Moiasa",
        "radio" : "VC0",
        "checkbox" : true,
        "invitations" : 6
    },
    "diarie" : {
        "number" : "HS 240-2015"
    }
}

=== jensaug/java-poi-utility/target/classes/json-samples/Extra/measurements/preem/suborders/norrbottenslanslandsting.json
{
  "dn": "o=Norrbottens läns landsting,st=Norra regionen,c=Sverige",
  "measurement": {
    "name": "Standardiserade vårdförlopp inom cancervård 2016",
    "grouping": "Standardiserade vårdförlopp inom cancervård",
    "period": "2016"
  },
  "selectionCriterias": [{
    "name": "Alla",
    "versions": [{
      "name": "vuxen",
      "questionnaire": {
        "name": "Specialiserad sjukhusvård öppen vuxen 2.0"
      }
    }]
  }],
  "organisations": [{
    "dn": "ou=Cancer i urinblåsa och övre urinvägar,o=Norrbottens läns landsting,st=Norra regionen,c=Sverige",
    "hsaId": "",
    "invitation": {
      "softName": "Norrbottens läns landsting"
    },
    "specific": {
      "managerEmails": ["roger.brannstrom@nll.se"]
    },
    "publicDn": "ou=Cancer i urinblåsan och övre urinvägarna,o=Norrbottens läns landsting,o=RCC Norr,c=Sverige",
    "metadata": {
      "producer": "Landstingsdrivet",
      "doneEdit": true
    },
    "alternativeId": "VK1"
  }, {
    "dn": "ou=Huvud och halscancer,o=Norrbottens läns landsting,st=Norra regionen,c=Sverige",
    "previousDn": "",
    "publicDn": "ou=Huvud- och halscancer,o=Norrbottens läns landsting,o=RCC Norr,c=Sverige",
    "invitation": {
      "softName": "Norrbottens läns landsting"
    },
    "hsaId": "",
    "specific": {
      "managerEmails": ["Susanna.Marklund@nll.se"]
    },
    "metadata": {
      "producer": "Landstingsdrivet",
      "doneEdit": true
    },
    "alternativeId": "VA9"
  }, {
    "dn": "ou=Matstrups- och magsäckscancer,o=Norrbottens läns landsting,st=Norra regionen,c=Sverige",
    "previousDn": "",
    "publicDn": "ou=Matstrups- och magsäckscancer,o=Norrbottens läns landsting,o=RCC Norr,c=Sverige",
    "invitation": {
      "softName": "Norrbottens läns landsting"
    },
    "hsaId": "",
    "specific": {
      "managerEmails": ["Marcus.Sunden@nll.se"]
    },
    "metadata": {
      "producer": "Landstingsdrivet",
      "doneEdit": true
    },
    "alternativeId": "VB0"
  }, {
    "dn": "ou=Akut myeloisk leukemi (AML),o=Norrbottens läns landsting,st=Norra regionen,c=Sverige",
    "previousDn": "",
    "publicDn": "ou=Akut myeloisk leukemi (AML),o=Norrbottens läns landsting,o=RCC Norr,ou=Sverige",
    "hsaId": "",
    "specific": {
      "managerEmails": ["birgitta.lauri@nll.se"]
    },
    "invitation": {
      "softName": "Norrbottens läns landsting"
    },
    "metadata": {
      "producer": "Landstingsdrivet",
      "doneEdit": true
    },
    "alternativeId": "VN6"
  }, {
    "metadata": {
      "doneEdit": true
    },
    "hsaId": "SE2321000230-E00001",
    "dn": "o=Norrbottens läns landsting,st=Norra regionen,c=Sverige",
    "specific": {
      "managerEmails": ["Michael.Dahlberg@nll.se", "carina.eriksson@nll.se", "eva.sjolund@nll.se"]
    }
  }, {
    "dn": "ou=Prostatacancer,o=Norrbottens läns landsting,st=Norra regionen,c=Sverige",
    "previousDn": "",
    "publicDn": "ou=Prostatacancer,o=Norrbottens läns landsting,o=RCC Norr,c=Sverige",
    "invitation": {
      "softName": "Norrbottens läns landsting"
    },
    "hsaId": "",
    "specific": {
      "managerEmails": ["Roger.Brannstrom@nll.se"]
    },
    "metadata": {
      "producer": "Landstingsdrivet",
      "doneEdit": true
    },
    "alternativeId": "VJ1"
  }],
  "alternativeIdSystem": "KVÅ kod",
  "specific": {
    "signedBy": "Eva Sjölund",
    "invitations": 1040
  }
}

=== jensaug/java-poi-utility/target/classes/json-samples/Extra/ssv2015-gavleborg-suborder.json
{
    "measurement": {
        "name": "Somatik slutenvård 2015 Region Gävleborg",
        "grouping": "Somatik slutenvård",
        "period": "2015"
    },
    "dn": "o=Landstinget Gävleborg,st=Uppsala-Örebro regionen,c=Sverige",
    "selectionCriterias": [
        {
            "name": "Somatik slutenvård",
            "versions": [
                {
                  "name": "Alla",
                  "questionnaire": {
                    "name": "Specialiserad sjukhusvård sluten v2.0"
                  }
                }
            ]
        }
    ],
    "organisations": [
        {
          "dn": "o=Landstinget Gävleborg,st=Uppsala-Örebro regionen,c=Sverige"
        }    
    ]
}

=== jensaug/java-poi-utility/target/classes/json-samples/Extra/measurements/patientnamnden/suborders/2016-orebro.json
{
  "dn": "o=Region Gotland,st=Stockholms sjukvårdsregion,c=Sverige",
  "measurement": {
    "name": "Patientnämnden 2016",
    "grouping": "Patientnämnden",
    "period": "2016"
  },
  "selectionCriterias": [
    {
      "name": "Alla",
      "versions": [
        {
          "name": "Alla",
          "questionnaire": {
            "name": "Patientnämnden 2.0"
          }
        }
      ]
    }
  ],
  "organisations": [
    {
      "dn": "o=Region Gotland,st=Stockholms sjukvårdsregion,c=Sverige"
    }
  ]
}
