=== jensaug/java-poi-utility/src/main/resources/schema/dimensionScore.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "_id": {
            "type": "string"
        },
        "measurement": {
            "type": "string"
        },
        "securityContext": {
            "type": "string"
        },
        "aspect": {
            "type": "string"
        },
        "dn": {
            "type": "string"
        },
        "filters": {
            "type": "string"
        },
        "status": {
            "type": "string"
        },
        "hsaId": {
            "type": "string"
        },
        "comment": {
            "type": "string"
        },
        "dimensions": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "percentagesPositive": {
            "type": "array",
            "items": {
                "type": "number"
            }
        },
        "trends": {
            "type": "array",
            "items": {
                "type": "number"
            }
        },
        "invitees": {
            "type": "object",
            "properties": {
                "answered": {
                    "type": "number"
                },
                "invited": {
                    "type": "number"
                },
                "invitedAdjusted": {
                    "type": "number"
                },
                "answeredPercentage": {
                    "type": "number"
                },
                "answeredAdjustedPercentage": {
                    "type": "number"
                }
            },
            "required": [
                "answered",
                "invited",
                "invitedAdjusted",
                "answeredPercentage",
                "answeredAdjustedPercentage"
            ],
            "additionalProperties": false
        }
    },
    "required": [
        "measurement",
        "aspect",
        "dn",
        "status",
        "dimensions",
        "invitees"
    ],
    "oneOf": [
        {
            "required": ["comment"]
        },
        {
            "required": ["percentagesPositive"]
        }
    ],
    "additionalProperties": false
}

=== jensaug/java-poi-utility/target/classes/json-samples/dimensionScore.json
{
    "measurement": "Primärvård 2016",
    "securityContext": "public",
    "aspect": "public",
    "dn": "c=Sverige",
    "filters": "selectionCriteria:Läkarbesök, version:vuxen",
    "status": "ok",
    "hsaId": "SE2321000131-E000000007687",
    "dimensions": [ 
        "Helhetsintryck", 
        "Emotionellt stöd", 
        "Delaktighet och involvering", 
        "Respekt och bemötande", 
        "Kontinuitet och koordinering", 
        "Information och kunskap", 
        "Tillgänglighet"
    ],
    "percentagesPositive": [ 
        79, 
        70, 
        79, 
        84, 
        69, 
        73, 
        81
    ],
    "invitees": {
        "answered": 79674,
        "invited": 186686,
        "invitedAdjusted": 185793,
        "answeredPercentage": 42.7,
        "answeredAdjustedPercentage": 42.9
    },
    "trends": [ 
        -1, 
        -1, 
        1, 
        -1, 
        0, 
        -1, 
        1
    ]
}
