=== jensaug/java-poi-utility/src/main/resources/schema/processInstance.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "definitions": {
        "naturalKey": {
            "type": "object",
            "properties": {
                "process": {
                    "type": "object",
                    "properties": {
                        "name": {
                            "type": "string"
                        },
                        "parentState": {
                            "type": "string"
                        }
                    },
                    "additionalProperties": false,
                    "required": ["name", "parentState"]
                },
                "dn": {
                    "type": "string"
                }
            },
            "required": ["process", "dn"]
        },
        "measurement": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "grouping": {
                    "type": "string"
                },
                "period": {
                    "type": "string"
                }
            },
            "additionalProperties": false,
            "required": ["name", "grouping", "period"]
        }
    },
    "type": "object",
    "allOf": [
        {
            "$ref": "#/definitions/naturalKey"
        },
        {
            "properties": {
                "_id": {
                    "id": "_id",
                    "type": "string"
                },   
                "hsaId": {
                    "type": "string"
                },                
                "measurement": {
                    "type": "object",
                    "properties": {
                        "/": {
                            "$ref": "#/definitions/measurement"
                        }
                    }
                },
                "open": {
                    "type": "string"
                },
                "close": {
                    "type": "string"
                },
                "currentState": {
                    "type": "string"
                },
                "created": {
                    "type": "string"
                }
            }
            }
        ],
    "properties": {
        "_id" : {},        
        "process": {},
        "hsaId": {},
        "dn": {},
        "measurement": {},
        "open": {},
        "close": {},
        "currentState": {},
        "created": {}
    },
    "additionalProperties": false,
    "required": ["process", "dn", "measurement", "currentState"]
}

=== jensaug/java-poi-utility/target/classes/json-samples/Extra/sov2015-gavleborg-processInstance.json
{
    "process": {
        "name": "Sammanställ mätningsunderlag för postal enkät",
        "parentState": "Sammanställ mätningsunderlag"
    },
    "dn": "o=Landstinget Gävleborg,st=Uppsala-Örebro regionen,c=Sverige",
    "measurement": {
        "name": "Somatik öppenvård 2015 Region Gävleborg",
        "grouping": "Somatik öppenvård",
        "period": "2015"
    },
    "open": "2015-10-01",
    "close": "2015-10-13",
    "currentState": "Välj grunddata"
}

=== jensaug/java-poi-utility/src/main/resources/json-samples/processInstance.json
{
    "process": {
        "name": "Sammanställ mätningsunderlag för postal enkät",
        "parentState": "Sammanställ mätningsunderlag"
    },
    "hsaId": "SE2321000131-E000000000001",    
    "dn": "o=Västra Götalandsregionen,st=Västra regionen,c=Sverige",
    "measurement": {
        "name": "Primärvård 2015",
        "grouping": "Primärvård",
        "period": "2015"
    },
    "open": "2015-05-01",
    "close": "2015-07-01",
    "currentState": "Godkänn sammanställning"
}
