=== jensaug/java-poi-utility/src/main/resources/schema/questionModule.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "object",
    "properties": {
        "_id": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "shortName": {
            "type": "string"
        },
        "comments": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "tags": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "questions": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "comparableText": {
                        "type": "string"
                    },
                    "description": {
                        "type": "string"
                    },
                    "status": {
                        "type": "string"
                    },
                    "dimension": {
                        "type": "string"
                    },
                    "choiceFreeText": {
                        "type": "boolean"
                    },
                    "choices": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "value": {
                                    "type": "string"
                                },
                                "weight": {
                                    "type": ["number", "null"]
                                }
                            },
                            "additionalProperties": false,
                            "required": [
                                "value"
                            ]
                        }
                    },
                    "customCodes": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "code": {
                                    "type": "string"
                                },
                                "vendor": {
                                    "type": "string"
                                }
                            },
                            "additionalProperties": false,
                            "required": [
                                "code",
                                "vendor"
                            ]
                        }
                    },
                    "comments": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "tags": {
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    }
                },
                "additionalProperties": false,
                "required": [
                    "comparableText"
                ]
            }
        },
        "languages": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "language": {
                        "type": "object",
                        "properties": {
                            "name": {
                                "type": "string"
                            },
                            "code": {
                                "type": "string"
                            }
                        },
                        "additionalProperties": false,
                        "required": [
                            "name",
                            "code"
                        ]
                    },
                    "variables": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "placeholder": {
                                    "type": "string"
                                },
                                "description": {
                                    "type": "string"
                                },
                                "choices": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                }
                            },
                            "additionalProperties": false,
                            "required": [
                                "placeholder",
                                "choices"
                            ]
                        }
                    },
                    "questions": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "comparableText": {
                                    "type": "string"
                                },
                                "text": {
                                    "type": "string"
                                },
                                "explanation": {
                                    "type": "string"
                                },
                                "group": {
                                    "type": "string"
                                },
                                "part": {
                                    "type": "string"
                                },
                                "elaboration": {
                                    "type": "object",
                                    "properties": {
                                        "text": {
                                            "type": "string"
                                        },
                                        "reference": {
                                            "type": "string"
                                        }
                                    },
                                    "additionalProperties": false,
                                    "required": [
                                        "text"
                                    ]
                                },
                                "choices": {
                                    "type": "array",
                                    "items": {
                                        "type": "object",
                                        "properties": {
                                            "value": {
                                                "type": "string"
                                            },
                                            "text": {
                                                "type": "string"
                                            }
                                        },
                                        "additionalProperties": false,
                                        "required": [
                                            "value"
                                        ]
                                    }
                                }
                            },
                            "additionalProperties": false,
                            "required": [
                                "comparableText",
                                "text"
                            ]
                        }
                    }
                },
                "additionalProperties": false,
                "required": [
                    "language",
                    "variables",
                    "questions"
                ]
            }
        }
    },
    "additionalProperties": false,
    "required": [
        "name",
        "shortName",
        "questions",
        "languages"
    ]
}

=== jensaug/java-poi-utility/src/main/resources/json-samples/questionModule.json
{
    "name": "questionmodule-sample",
    "shortName": "qms",
    "comments": [
        "Denna frågemodul är ett exempel"
    ],
    "tags": [
        "ex"
    ],
    "questions": [
        {
            "comparableText": "Skulle du rekommendera ${verksamheten} till vänner och bekanta?",
            "description": "detta är en fråga",
            "status": "LEGACY",
            "dimension": "Delaktighet och involvering",
            "choiceFreeText": false,
            "choices": [
                {
                    "value": "1",
                    "weight": -1
                },
                {
                    "value": "2",
                    "weight": -1
                },
                {
                    "value": "3",
                    "weight": 0
                },
                {
                    "value": "4",
                    "weight": 1
                },
                {
                    "value": "5",
                    "weight": 1
                },
                {
                    "value": "6"
                }
            ],
            "customCodes": [
                {
                    "code": "DBNVNA05YNNNA1N000054",
                    "vendor": "icquality"
                }
            ],
            "comments": [
                "Denna fråga är väldigt fin",
                "Jag tycker om denna fråga"
            ],
            "tags": [
                "ex"
            ]
        },
        {
            "comparableText": "Har du andra synpunkter eller vill utveckla dina svar?",
            "choiceFreeText": true
        }
    ],
    "languages": [
        {
            "language": {
                "name": "Svenska",
                "code": "sv_SE"
            },
            "variables": [
                {
                    "placeholder": "verksamheten",
                    "description": "Ange vilken typ av enhet som frågan gäller för",
                    "choices": [
                        "hälso-/vårdcentralen",
                        "sjukhuset"
                    ]
                }
            ],
            "questions": [
                {
                    "comparableText": "Skulle du rekommendera ${verksamheten} till vänner och bekanta?",
                    "text": "Skulle du: rekommendera ${verksamheten} till vänner och bekanta?",
                    "explanation": "Var god skriv inom rutans ramar, texta tydligt.",
                    "group": "Skulle du:",
                    "part": "rekommendera ${verksamheten} till vänner och bekanta?",
                    "elaboration": {
                        "text": "Utveckla gärna ditt svar på sista sidan",
                        "reference": "Har du andra synpunkter eller vill utveckla dina svar?"
                    },
                    "choices": [
                        {
                            "text": "Nej, inte alls",
                            "value": "1"
                        },
                        {
                            "value": "2"
                        },
                        {
                            "value": "3"
                        },
                        {
                            "value": "4"
                        },
                        {
                            "text": "Ja, helt och hållet",
                            "value": "5"
                        },
                        {
                            "text": "Ej aktuellt",
                            "value": "6"
                        }
                    ]
                },
                {
                    "comparableText": "Har du andra synpunkter eller vill utveckla dina svar?",
                    "text": "Har du andra synpunkter eller vill utveckla dina svar?"
                }
            ]
        }
    ]
}
